#+title: Extra words
#+created: 2026-07-21T00:54:00+0900

Words collected from other places.

This code block will export the words into a CSV that can be imported into TaigiKeyboard as custom words.

Words are in “begin_src words” blocks (source code blocks using “words” as the language). Lines starting with “#” are comments (ignored). Each line is one word entry, separated by tab; the fields are hanlo, tsuanlo, input form, and weight (optional).

#+begin_src elisp
(require 'org-element)
(require 's)
(require 'dash)

(defun k/call-process-to-string (command &rest args)
  "Call COMMAND with ARGS; return stdout.

If COMMAND returns with a non-zero exit code, signal an error."
  (declare (indent 0))
  (with-temp-buffer
    (let ((code (apply #'call-process command nil '(t nil) nil args)))
      (unless (= 0 code)
        (error "%s exited with exit code %s" command code)))
    (string-trim (buffer-string))))

(defun k/write-words (target)
  "Write words in this buffer into the path TARGET."
  (save-excursion
    (goto-char (point-min))
    (let ((out-lines nil))
      (while (re-search-forward "^#\\+begin_src words$" nil t)
        (cl-loop
         for line in (--> (org-element-at-point)
                          (org-element-property :value it)
                          s-trim
                          (s-split "\n" it t))
         unless (s-starts-with? "#" line)
         do
         (-let* (((han tl) (s-split "\t" line)))
           (push (format "%s,%s" tl han)
                 out-lines)))
        ;; Put an empty line between output lines corresponding to different
        ;; input blocks
        (push "" out-lines))
      (with-temp-file target
        (insert (->> (nreverse out-lines)
                     -uniq
                     (s-join "\n"))
                "\n")))))

(k/write-words "taigikeyboard-custom.csv")
#+end_src

#+RESULTS:

* My own

#+begin_src words
正齒	tsiànn-khí
倒齒	tó-khí
中齒	tiong-khí
頁面	ia̍h-bīn
光碟	kng-tia̍p
磁碟	tsû-tia̍p
遠端	uán-tuan
重啟動	tîng-khé-tōng
社群	siā-kûn
khóo-pih	khóo-pih
資料鋏仔	tsu-liāu-giap-á
操作系統	tshau-tsok-hē-thóng	5
應用程式	ìng-iōng-tîng-sik
簡略	kán-lio̍k
儲存	tû-tsûn
移除	î-tû
# Same weight as 使用者
用者	iōng-tsiá	14
所有者	sóo-iú-tsiá
管理者	kuán-lí-tsiá
索引器	sik-ín-khì
管理器	kuán-lí-khì
啟動器	khé-tōng-khì
停用	thîng-iōng
#+end_src

* Taigi-STEM

https://hackmd.io/@TaigiSTEM/math/https%3A%2F%2Fhackmd.io%2F%40TaigiSTEM%2Farithmetic

#+begin_src words
九九合數	kiú-kiú-ha̍p-sòo
九九算	kiú-kiú-suàn
#+end_src

| 台漢   | 台羅          | 華語   | 英語               | 日語   |
|-------+--------------+-------+-------------------+-------|
| 自然數 | tsū-jiân-sòo | 自然數 | natural number    | 自然数 |
| 整數   | tsíng-sòo    | 整數   | integer           | 整数   |
| 有比數 | iú-pí-sòo    | 有理數 | rational number   | 有理数 |
| 無比數 | bû-pí-sòo    | 無理數 | irrational number | 無理数 |
| 實數   | si̍t-sòo      | 實數   | real number       | 実数   |
| 虛數   | hi-sòo       | 虛數   | imaginary number  | 虚数   |
| 複合數 | ho̍k-ha̍p-sòo  | 複數   | complex number    | 複素数 |
| 四元數 | sì-guân-sòo  | 四元數 | quaternion        | 四元数 |
| 八元數 | peh-guân-sòo | 八元數 | octonion          | 八元数 |

#+begin_src words
自然數	tsū-jiân-sòo
整數	tsíng-sòo
有比數	iú-pí-sòo
無比數	bû-pí-sòo
實數	si̍t-sòo
虛數	hi-sòo
複合數	ho̍k-ha̍p-sòo
四元數	sì-guân-sòo
八元數	peh-guân-sòo
#+end_src

| 台漢       | 台羅                    | 華語       | 英語                | 日語           |
|------------+-------------------------+------------+---------------------+----------------|
| 循環小數   | sûn-khuân sió-sòo       | 循環小數   | repeating decimal   | 循環小数       |
| 有限小數   | iú-hān sió-sòo          | 有限小數   | terminating decimal | 有限小数       |
| 稠密性     | tiû-bi̍t-sìng            | 稠密性     | denseness           | 稠密性         |
| 離散性     | lī-sàn-sìng             | 離散性     | discreteness        | 離散性         |
| 完全平方數 | uân-tsuân pîng-hong sòo | 完全平方數 | perfect square      | （完全）平方数 |

#+begin_src words
循環小數	sûn-khuân sió-sòo
有限小數	iú-hān sió-sòo
稠密性	tiû-bi̍t-sìng
離散性	lī-sàn-sìng
完全平方數	uân-tsuân pîng-hong sòo
#+end_src

#+begin_src words
概數	kài-sòo
#+end_src
