#+title: Extra words
#+created: 2026-07-21T00:54:00+0900

Words collected from other places.

This code block will export the words into a usable Rime dict.

Words are in “begin_src words” blocks (source code blocks using “words” as the language). Lines starting with “#” are comments (ignored). Each line is one word entry, separated by tab; the fields are hanlo, tsuanlo, input form, and weight (optional).

#+begin_src elisp
(require 'org-element)
(require 's)
(require 'dash)

(defun k/call-process-to-string (command &rest args)
  "Call COMMAND with ARGS; return stdout.

If COMMAND returns with a non-zero exit code, signal an error."
  (declare (indent 0))
  (with-temp-buffer
    (let ((code (apply #'call-process command nil '(t nil) nil args)))
      (unless (= 0 code)
        (error "%s exited with exit code %s" command code)))
    (string-trim (buffer-string))))

(defun k/pn-to-input-form (pn)
  "Convert PN to input form (with numbered tones), preserving tones.
This just shells out to processing/pnToInputForm.ts using Node."
  (k/call-process-to-string "node" "processing/pnToInputForm.ts" pn))

(defun k/write-words (target &optional dict-name dict-description)
  "Write words in this buffer into the path TARGET.
If DICT-NAME is non-nil, write TARGET as a Rime dict named as NAME.
If DICT-DESCRIPTION is also non-nil, use it as the prelude comment of
the resulting Rime dict."
  ;; Each word will get 6 entries:
  ;; 2 forms (TL or Han characters)
  ;; times 3 variants (all uppercase, all lowercase, capitalize first)
  (save-excursion
    (goto-char (point-min))
    (let ((out-lines nil))
      (while (re-search-forward "^#\\+begin_src words$" nil t)
        (let ((cap-first (lambda (s)
                           (if (= (length s) 0)
                               s
                             (concat (upcase (substring s 0 1))
                                     (downcase (substring s 1)))))))
          (cl-loop
           for line in (--> (org-element-at-point)
                            (org-element-property :value it)
                            s-trim
                            (s-split "\n" it t))
           unless (s-starts-with? "#" line)
           do
           (-let* (((han tl weight) (s-split "\t" line))
                   (input-form (k/pn-to-input-form tl)))
             (dolist (out (list han tl))
               (dolist (func `(downcase ,cap-first upcase))
                 (push (format "%s\t%s\t%s"
                               (funcall func out)
                               (funcall func input-form)
                               (or weight 1))
                       out-lines))))))
        ;; Put an empty line between output lines corresponding to different
        ;; input blocks
        (push "" out-lines))
      (with-temp-file target
        (when dict-name
          (when dict-description
            (dolist (line (s-split "\n" dict-description))
              (insert (format "# %s\n" line))))
          (insert (format "---
name: %s
version: \"1.0\"
sort: by_weight
use_preset_vocabulary: false
...\n" dict-name)))
        (insert (->> (nreverse out-lines)
                     -uniq
                     (s-join "\n")))))))

(k/write-words "hanlo-extra.dict.yaml" "hanlo-extra" "Extra words compiled in kemdict/taigi-playground.")
#+end_src

#+RESULTS:

* My own

#+begin_src words
所有者	sóo-iú-tsiá
枋模	pang-pôo
遠端	uán-tuan
khóo-pih	khóo-pih
資料鋏仔	tsu-liāu-giap-á
# Same weight as 使用者
用者	iōng-tsiá	14
終端機	tsiong-tuan-ki
開發者	khai-huat-tsiá
操作系統	tshau-tsok-hē-thóng	5
快速齒	khuài-sok-khí	1
應用程式	îng-ióng-tîng-sik
隱藏	ún-tsông
字元	jī-guân
管理者	kuán-lí-tsiá
伺服器	sù-ho̍k-khì
瀏覽	liû-lám
瀏覽器	liû-lám-khì
#+end_src

* Taigi-STEM

https://hackmd.io/@TaigiSTEM/math/https%3A%2F%2Fhackmd.io%2F%40TaigiSTEM%2Farithmetic

#+begin_src words
九九合數	kiú-kiú-ha̍p-sòo
九九算	kiú-kiú-suàn
#+end_src

| 台漢   | 台羅          | 華語   | 英語               | 日語   |
|-------+--------------+-------+-------------------+-------|
| 自然數 | tsū-jiân-sòo | 自然數 | natural number    | 自然数 |
| 整數   | tsíng-sòo    | 整數   | integer           | 整数   |
| 有比數 | iú-pí-sòo    | 有理數 | rational number   | 有理数 |
| 無比數 | bû-pí-sòo    | 無理數 | irrational number | 無理数 |
| 實數   | si̍t-sòo      | 實數   | real number       | 実数   |
| 虛數   | hi-sòo       | 虛數   | imaginary number  | 虚数   |
| 複合數 | ho̍k-ha̍p-sòo  | 複數   | complex number    | 複素数 |
| 四元數 | sì-guân-sòo  | 四元數 | quaternion        | 四元数 |
| 八元數 | peh-guân-sòo | 八元數 | octonion          | 八元数 |

#+begin_src words
自然數	tsū-jiân-sòo
整數	tsíng-sòo
有比數	iú-pí-sòo
無比數	bû-pí-sòo
實數	si̍t-sòo
虛數	hi-sòo
複合數	ho̍k-ha̍p-sòo
四元數	sì-guân-sòo
八元數	peh-guân-sòo
#+end_src

| 台漢       | 台羅                    | 華語       | 英語                | 日語           |
|------------+-------------------------+------------+---------------------+----------------|
| 循環小數   | sûn-khuân sió-sòo       | 循環小數   | repeating decimal   | 循環小数       |
| 有限小數   | iú-hān sió-sòo          | 有限小數   | terminating decimal | 有限小数       |
| 稠密性     | tiû-bi̍t-sìng            | 稠密性     | denseness           | 稠密性         |
| 離散性     | lī-sàn-sìng             | 離散性     | discreteness        | 離散性         |
| 完全平方數 | uân-tsuân pîng-hong sòo | 完全平方數 | perfect square      | （完全）平方数 |

#+begin_src words
循環小數	sûn-khuân sió-sòo
有限小數	iú-hān sió-sòo
稠密性	tiû-bi̍t-sìng
離散性	lī-sàn-sìng
完全平方數	uân-tsuân pîng-hong sòo
#+end_src
